#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRazorMediatorLayouts
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    
    
    public partial class WrappedTridionRazorTemplate
    {

#line 4 "..\..\Views\Shared\MainHelpers.cshtml"
public System.Web.WebPages.HelperResult TestHelper(string test)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 5 "..\..\Views\Shared\MainHelpers.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    ");

WriteLiteralTo(__razor_helper_writer, "<h1>");


#line 6 "..\..\Views\Shared\MainHelpers.cshtml"
WriteTo(__razor_helper_writer, test);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</h1>\r\n");


#line 7 "..\..\Views\Shared\MainHelpers.cshtml"


#line default
#line hidden
});

#line 7 "..\..\Views\Shared\MainHelpers.cshtml"
}
#line default
#line hidden

        
        
    }
}
#pragma warning restore 1591
